name: Upload to Swarm

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install HTTrack
        run: sudo apt-get update && sudo apt-get install -y httrack
      - name: Build Static Export
        run: |
          npm ci
          npm run clone
      # Install swarm-cli globally
      - name: Install swarm-cli
        run: npm install -g @ethersphere/swarm-cli
      # Upload the ./output/devcon-local/ directory using swarm-cli
      - name: Upload to Swarm
        run: |
          swarm-cli upload ./output/devcon-local/ \
            --bee-api-url ${{ secrets.PRIVATE_BEE_URL }} \
            --stamp ${{ secrets.PRIVATE_POSTAGE_BATCH_ID }} \
            --redundancy PARANOID \
            --pin --yes
